### ISSUE TITLE
Does not work in android processing mode

### ISSUE THREAD

**Issue by Harvie** [processing/processing-sound-archive#119]
Does not work in android processing mode

**Comment by narner** [comment]
Same for me - when running the examples in the X86 Android simulator on macOS, I get the following error logs: 

```
BUILD SUCCESSFUL in 7s
35 actionable tasks: 35 executed
FATAL EXCEPTION: Animation Thread
Process: processing.test.pulsewidth, PID: 2878
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/processing.test.pulsewidth-WIBvAfprBEaaoT-kMFy7fQ==/base.apk"],nativeLibraryDirectories=[/data/app/processing.test.pulsewidth-WIBvAfprBEaaoT-kMFy7fQ==/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libMethClaInterface.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
	at java.lang.System.loadLibrary(System.java:1657)
	at processing.sound.MethClaInterface.<clinit>(Unknown Source:109)
	at processing.sound.Engine.<init>(Unknown Source:3)
	at processing.sound.Engine.<init>(Unknown Source:0)
	at processing.sound.Engine$LazyHolder.<clinit>(Unknown Source:3)
	at processing.sound.Engine$LazyHolder.access$100(Unknown Source:0)``
	at processing.sound.Engine.start(Unknown Source:0)
	at processing.sound.Pulse.<init>(Unknown Source:47)
	at processing.test.pulsewidth.PulseWidth.setup(PulseWidth.java:37)
	at processing.core.PApplet.handleDraw(Unknown Source:74)
	at processing.core.PSurfaceNone.callDraw(Unknown Source:19)
	at processing.core.PSurfaceNone$AnimationThread.run(Unknown Source:55)
```
