### ISSUE TITLE
v1.3 "relies on native code that's not available"

### ISSUE THREAD

**Issue by markstock** [processing/processing-sound-archive#45]
My Processing (3.0b2) sketch was running with sound v1.2.1 on linux64. The large number of repeating sound files are causing lots of "ERROR: /node/free: Node id -1 out of range" errors, and even crashing the sketch on OSX, so I decided to try out v1.3 (downloaded and unzipped sound.zip, and dropped it right in sketchbook/libraries/ where the old one was). Right out of the box, my sketch does not run, but instead gives me the following error:

```
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit  application.
```

Any idea whats going wrong?

**Comment by wirsing** [comment]
i'll check into this, that shouldn't be happening.

**Comment by markstock** [comment]
Same problem in Processing 3.0b5 (Linux). Both work with 1.2.1. Error that I see reads:

```
Exception in thread "Animation Thread" java.lang.UnsatisfiedLinkError: processing.sound.MethClaInterface.busConstructMono()I
    at processing.sound.MethClaInterface.busConstructMono(Native Method)
    at processing.sound.Engine.busConstructMono(Unknown Source)
    at processing.sound.SoundFile.<init>(Unknown Source)
    at performerIPcamera.setup(performerIPcamera.java:279)
    at processing.core.PApplet.handleDraw(PApplet.java:2376)
    at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1499)
    at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:312)
```

**Comment by wirsing** [comment]
yeah, that is a linking problem. i'll get on it! will let you know when a new version is out, probably soon! thanks for reporting!

**Comment by markstock** [comment]
Terrific. Thanks for the quick attention.

**Comment by kasperkamperman** [comment]
Same problem here. 

```
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit application.
```

Windows 10
processing-3.0b5 (64 bit)

**Comment by AMDFreak2006** [comment]
Any chance this gets fixed within october? or is there a way to get an older, functioning release of the library as a workaround as long as the bug is not fixed?

thanks in advance!

**Comment by wirsing** [comment]
Please use v.1.2.1 for now, I am working on it.

all the best,
Wilm

**Comment by AMDFreak2006** [comment]
How/where can I get Version 1.2.1? I can't find it in the Processing IDE and here in Github I can't find a 1.2.1-folder neither.

Thanks in advance.

**Comment by AMDFreak2006** [comment]
thanks :)

btw: the latest release (1.3.1) is not useable in Processing neither.
You can install it and after a restart of Processing it says its not installed and it doesn't show up in the "examples"-browser. Using 1.2.1 works.

**Comment by wirsing** [comment]
that should be fixed now. i reverted linux64 to 1.2.1 and windows64 as well. can you try again?

**Comment by ezawadzki** [comment]
Is the 1.3 Sound Library has been reverted to 1.2.1 ?
Because I've just tested on windows64 and ubuntu64, I get the same issue.

**Comment by hamoid** [comment]
Do we need to manually install an older version until the working version is displayed in the library list inside Processing?

**Comment by robotbambi** [comment]
I am still seeing this problem as well on Windows 10. I used 1.2.1 as a workaround, but after the application has been running for 5-10 minutes, the program crashes with the JRE fatal error noted in issue #57.

**Comment by serebit** [comment]
I am still seeing this problem as well on OS X 10.11. It does not cause a crash, but does give me a lot of "ERROR: /node/free: Node id -1 out of range" console messages upon closing the program.

**Comment by AnastasiaDunbar** [comment]
```
Error: Soundfile doesn't exist. Pleae check path
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit application.
```

Windows 8 64-bit 3.0.1
Also getting the error, and a misspelling of "Please".

**Comment by susanneamalie** [comment]
Has anyone found a solution to this yet?

I'm having the same issues with win8/64 bit - have tried both version 1.3.1 and 1.2.1.

This is super-annoying...!

**Comment by schellenberg** [comment]
I get the same error:
`Error: Soundfile doesn't exist. Pleae check path
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit application.`

Windows 81. 64-bit 3.0.1

**Comment by rl777** [comment]
Having fun learning Processing. Running v 3.0.1 64-bit on Windows 10. No problems until I tried working with sounds. Installed the Sound Library Got same error others have reported. "A library relies on native code that's not available. Or only works properly when the sketch is run as a 32-bit application."

# Here are the library's properties:

name=Sound
category=Sound
authors=The Processing Foundation
url=http://processing.org/reference/libraries/sound/index.html
sentence=Sound library based on MethCla for Processing.
paragraph=
version=6
prettyVersion=1.3.1
lastUpdated=0
minRevision=228
maxRevision=0

**Comment by timkaboya** [comment]
Anyone found a solution to this error yet? 
I am getting the same problem. 
Cant run sound.

**Comment by emnullfuenf** [comment]
Unfortunately all students using Windows in my creative coding class had this problem. We had to switch back to Minim.
Can i help fixing / texting?

**Comment by RitualSSB** [comment]
Using  the Sound library version 1.4 on MacOS High Sierra, I am currently getting a:

ERROR: /node/free: Node id -1 out of range

Error, On loop in my console. This is the only related issue I have found here, on google, or on processing forums. Can I ask what this might mean?
