### ISSUE TITLE
Exception in thread "Animation Thread" java.lang.UnsatisfiedLinkError: no LIBWINPTHREAD-1 in java.library.path

### ISSUE THREAD

**Issue by rongloveyan** [processing/processing-sound-archive#89]
Exception in thread "Animation Thread" java.lang.UnsatisfiedLinkError: no LIBWINPTHREAD-1 in java.library.path
    at java.lang.ClassLoader.loadLibrary(Unknown Source)
    at java.lang.Runtime.loadLibrary0(Unknown Source)
    at java.lang.System.loadLibrary(Unknown Source)
    at processing.sound.MethClaInterface.<clinit>(MethClaInterface.java:43)
    at processing.sound.Engine.<init>(Engine.java:35)
    at processing.sound.Engine.<init>(Engine.java:33)
    at processing.sound.Engine$LazyHolder.<clinit>(Engine.java:41)
    at processing.sound.Engine.start(Engine.java:45)
    at processing.sound.SoundFile.<init>(SoundFile.java:55)
    at com.illuma.view.MyGImageButton.<init>(MyGImageButton.java:13)
    at com.illuma.Main.setup(Main.java:41)
    at processing.core.PApplet.handleDraw(PApplet.java:2379)
    at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1540)
    at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)

**Comment by ricardoboss** [comment]
You have to add the `library\{your_os}` to your classpath.
